services:
  schemesaathi-app:
    container_name: schemesaathi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - schemesathi-network

networks:
  schemesathi-network:
    driver: bridge
