services:
  schemesaathi-app:
    container_name: schemesaathi-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - schemesaathi-network

networks:
  schemesaathi-network:
    driver: bridge
